//
//  ViewController.swift
//  scroll-view
//
//  Created by maxim mironov on 15/04/2019.
//  Copyright © 2019 maxim mironov. All rights reserved.
//

import UIKit

class ViewController: UIViewController {

    @IBOutlet weak var lable: UILabel!
    @IBOutlet weak var textField: UITextField!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        lable.connect(with: textField)
        // Do any additional setup after loading the view.
//        lable.text = "lihsdiashuidasgdiags8dgasd7oaso8dgaysdlihsdiashuidasgdiags8dgasd7oaso8dgaysdlihsdiashuidasgdiags8dgasd7oaso8dgaysdlihsdiashuidasgdiags8dgasd7oaso8dgaysdlihsdiashuidasgdiags8dgasd7oaso8dgaysdlihsdiashuidasgdiags8dgasd7oaso8dgaysdlihsdiashuidasgdiags8dgasd7oaso8dgaysdlihsdiashuidasgdiags8dgasd7oaso8dgaysdlihsdiashuidasgdiags8dgasd7oaso8dgaysdlihsdiashuidasgdiags8dgasd7oaso8dgaysdlihsdiashuidasgdiags8dgasd7oaso8dgaysdlihsdiashuidasgdiags8dgasd7oaso8dgaysdlihsdiashuidasgdiags8dgasd7oaso8dgaysdlihsdiashuidasgdiags8dgasd7oaso8dgaysdlihsdiashuidasgdiags8dgasd7oaso8dgaysdlihsdiashuidasgdiags8dgasd7oaso8dgaysdlihsdiashuidasgdiags8dgasd7oaso8dgaysdlihsdiashuidasgdiags8dgasd7oaso8dgaysdlihsdiashuidasgdiags8dgasd7oaso8dgaysdlihsdiashuidasgdiags8dgasd7oaso8dgaysdlihsdiashuidasgdiags8dgasd7oaso8dgaysdlihsdiashuidasgdiags8dgasd7oaso8dgaysdlihsdiashuidasgdiags8dgasd7oaso8dgaysdlihsdiashuidasgdiags8dgasd7oaso8dgaysdlihsdiashuidasgdiags8dgasd7oaso8dgaysdlihsdiashuidasgdiags8dgasd7oaso8dgaysdlihsdiashuidasgdiags8dgasd7oaso8dgaysdlihsdiashuidasgdiags8dgasd7oaso8dgaysdlihsdiashuidasgdiags8dgasd7oaso8dgaysdlihsdiashuidasgdiags8dgasd7oaso8dgaysdlihsdiashuidasgdiags8dgasd7oaso8dgaysdlihsdiashuidasgdiags8dgasd7oaso8dgaysdlihsdiashuidasgdiags8dgasd7oaso8dgaysdlihsdiashuidasgdiags8dgasd7oaso8dgaysdlihsdiashuidasgdiags8dgasd7oaso8dgaysdlihsdiashuidasgdiags8dgasd7oaso8dgaysdlihsdiashuidasgdiags8dgasd7oaso8dgaysdlihsdiashuidasgdiags8dgasd7oaso8dgaysdlihsdiashuidasgdiags8dgasd7oaso8dgaysdlihsdiashuidasgdiags8dgasd7oaso8dgaysdlihsdiashuidasgdiags8dgasd7oaso8dgaysdlihsdiashuidasgdiags8dgasd7oaso8dgaysdlihsdiashuidasgdiags8dgasd7oaso8dgaysdlihsdiashuidasgdiags8dgasd7oaso8dgaysdlihsdiashuidasgdiags8dgasd7oaso8dgaysdlihsdiashuidasgdiags8dgasd7oaso8dgaysdlihsdiashuidasgdiags8dgasd7oaso8dgaysdlihsdiashuidasgdiags8dgasd7oaso8dgaysdlihsdiashuidasgdiags8dgasd7oaso8dgaysdlihsdiashuidasgdiags8dgasd7oaso8dgaysdlihsdiashuidasgdiags8dgasd7oaso8dgaysdlihsdiashuidasgdiags8dgasd7oaso8dgaysdlihsdiashuidasgdiags8dgasd7oaso8dgaysdlihsdiashuidasgdiags8dgasd7oaso8dgaysdlihsdiashuidasgdiags8dgasd7oaso8dgaysdlihsdiashuidasgdiags8dgasd7oaso8dgaysdlihsdiashuidasgdiags8dgasd7oaso8dgaysdlihsdiashuidasgdiags8dgasd7oaso8dgaysdlihsdiashuidasgdiags8dgasd7oaso8dgaysdlihsdiashuidasgdiags8dgasd7oaso8dgaysdlihsdiashuidasgdiags8dgasd7oaso8dgaysdlihsdiashuidasgdiags8dgasd7oaso8dgaysdlihsdiashuidasgdiags8dgasd7oaso8dgaysdlihsdiashuidasgdiags8dgasd7oaso8dgaysdlihsdiashuidasgdiags8dgasd7oaso8dgaysdlihsdiashuidasgdiags8dgasd7oaso8dgaysdlihsdiashuidasgdiags8dgasd7oaso8dgaysdlihsdiashuidasgdiags8dgasd7oaso8dgaysdlihsdiashuidasgdiags8dgasd7oaso8dgaysdlihsdiashuidasgdiags8dgasd7oaso8dgaysdlihsdiashuidasgdiags8dgasd7oaso8dgaysdlihsdiashuidasgdiags8dgasd7oaso8dgayslihsdiashuidasgdiags8dgasd7oaso8dgaysdlihsdiashuidasgdiags8dgasd7oaso8dgaysdlihsdiashuidasgdiags8dgasd7oaso8dgaysdlihsdiashuidasgdiags8dgasd7oaso8dgaysdlihsdiashuidasgdiags8dgasd7oaso8dgaysdlihsdiashuidasgdiags8dgasd7oaso8dgaysdlihsdiashuidasgdiags8dgasd7oaso8dgaysdlihsdiashuidasgdiags8dgasd7oaso8dgaysdlihsdiashuidasgdiags8dgasd7oaso8dgaysdlihsdiashuidasgdiags8dgasd7oaso8dgaysdlihsdiashuidasgdiags8dgasd7oaso8dgaysdlihsdiashuidasgdiags8dgasd7oaso8dgaysdlihsdiashuidasgdiags8dgasd7oaso8dgaysdlihsdiashuidasgdiags8dgasd7oaso8dgaysdlihsdiashuidasgdiags8dgasd7oaso8dgaysdlihsdiashuidasgdiags8dgasd7oaso8dgaysdlihsdiashuidasgdiags8dgasd7oaso8dgaysdlihsdiashuidasgdiags8dgasd7oaso8dgaysdlihsdiashuidasgdiags8dgasd7oaso8dgaysdlihsdiashuidasgdiags8dgasd7oaso8dgaysdlihsdiashuidasgdiags8dgasd7oaso8dgaysdlihsdiashuidasgdiags8dgasd7oaso8dgaysdlihsdiashuidasgdiags8dgasd7oaso8dgaysdlihsdiashuidasgdiags8dgasd7oaso8dgaysdlihsdiashuidasgdiags8dgasd7oaso8dgaysdlihsdiashuidasgdiags8dgasd7oaso8dgaysdlihsdiashuidasgdiags8dgasd7oaso8dgaysdlihsdiashuidasgdiags8dgasd7oaso8dgaysdlihsdiashuidasgdiags8dgasd7oaso8dgaysdlihsdiashuidasgdiags8dgasd7oaso8dgaysdlihsdiashuidasgdiags8dgasd7oaso8dgaysdlihsdiashuidasgdiags8dgasd7oaso8dgaysdlihsdiashuidasgdiags8dgasd7oaso8dgaysdlihsdiashuidasgdiags8dgasd7oaso8dgaysdlihsdiashuidasgdiags8dgasd7oaso8dgaysdlihsdiashuidasgdiags8dgasd7oaso8dgays"
    }


}

